# Generated by Django 4.2.6 on 2023-11-14 19:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articulos_creador_cafeterias_creador_recetas_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
