# Generated by Django 4.2.6 on 2023-11-15 14:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_articulos_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='receta',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
