# Generated by Django 4.2.6 on 2023-11-15 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_recetas_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
