# Generated by Django 4.2.6 on 2023-11-15 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_articulos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='fecha',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
