# Generated by Django 4.2.6 on 2023-11-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_articulos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
